// CHSolitaire - Klondike for the CHGame handheld (CH32X035, 128x128 ST7735,
// piezo), after the Windows classic: draw one or three, Standard or Vegas
// scoring, a choice of card backs, and the cards bouncing away when you
// win. In the style of CHBlackjack, CHChess and CHPoker.
//
// The files:
//   Klondike.*           the rules and the scoring (no graphics: host-tested)
//   Stage.*              the table: the glove, the cards in flight, the cascade
//   CardArt.*, Layout.h  a card, its backs, and where everything sits
//   Screens.*            title, the table, the deck of backs, options, stats
//   Fx.*, Sounds.*       particles and banners, the sound effects
//   Save.*, config.h     what a save holds; build switches
//   src/assets/          the art, generated by tools/assets.py
//
// Frame loop: logic runs at a fixed 60 Hz while the previous frame is still
// going out over DMA; drawing waits for it (one framebuffer), then the new
// frame is sent.
#include <CHGame.h>
#include "config.h"
#include "Screens.h"
#include "Sounds.h"

void setup() {
    chgame.boot();
    dbg::begin("CHSO " CHSO_VERSION);     // the debug protocol's hello (CHGAME_DEBUG builds)
    gfx_begin(GFX_DIV2, GFX_12BPP);
    pal::init();
    screens::begin();
    chgame.setFrameRate(CHSO_FPS);
}

void loop() {
    dbg::poll();
    if (!chgame.nextFrame()) return;
    dbg::markUpdateStart();
    uint8_t ticks = 0;
    do {
        chgame.pollButtons();
        pal::tick();
        audio::update();
        screens::update();
    } while (++ticks < 3 && chgame.nextFrame());
    gfx_wait();
    pal::commit();
    dbg::markRenderStart();
    screens::render(chgame.frameCount);
    dbg::markRenderEnd();
    gfx_flushAsync();
}
