// GENERATED by tools/assets.py - do not edit.
// The dealer derives from Press-Play-On-Tape/Blackjack (Apache-2.0) by
// filmote & vampirics, recoloured 2026 for CHGame by bateske (CHBlackjack);
// the title lettering is new (tools/art/). See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t DEALER[463];
extern const uint8_t FACE_NORMAL[122];
extern const uint8_t CHIP_TOP[37];
extern const uint8_t CHIP_SIDE[25];
extern const uint8_t CHIP_SIDE_ALT[25];
extern const uint8_t CHIP_SMALL_TOP[31];
extern const uint8_t CHIP_SMALL_SIDE[15];
extern const uint8_t CHIP_SMALL_SIDE_ALT[15];
extern const uint8_t FIELD_PRINT[259];
extern const uint8_t PUCK_ON[60];
extern const uint8_t PUCK_OFF[71];
extern const uint8_t LOGO[375];
constexpr int LOGO_W = 118;
constexpr int LOGO_H = 25;
constexpr int LOGO_BASE = 8;
extern const uint8_t LOGO_RAMP[25];
constexpr int LOGO_DEPTH = 3;
constexpr int LOGO_SIDE = 7;
extern const uint16_t FACE_EDITS[165];
extern const uint16_t FACE_EDIT_AT[7];
