// GENERATED by tools/assets.py - do not edit.
// The croupier and the end-screen lettering are Press Play On Tape's
// (Apache-2.0, by filmote & vampirics), as recoloured for CHBlackjack; the
// glove is CHChess's; the rest was drawn for this game. See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t DEALER[463];  // the croupier 48x42, row spans
extern const uint8_t DEALER_ALT_REMAP[16];  // the NIGHT croupier: remap applied to DEALER
extern const uint8_t FACE_NORMAL[122];  // face patch 24x18 at (12,14), row spans
extern const uint16_t FACE_EDITS[196];  // expression edits: (y*24+x)<<4 | colour; ANGRY RAISED BLINK SMILE SURPRISED TALK
extern const uint16_t FACE_EDIT_AT[7];  // start of each expression in FACE_EDITS, plus end
extern const uint8_t HAND[111];  // the glove 13x16, row spans; fingertip on the bottom row
constexpr int HAND_TIP = 5;  // the fingertip's column
extern const uint8_t DOLLY[43];  // the dolly 5x9, row spans; foot centred on the bottom row
extern const uint8_t LOGO[255];  // 'ROULETTE': the cover's lettering, 115x17, 1 bpp MSB-first rows
constexpr int LOGO_W = 115;
constexpr int LOGO_H = 17;
constexpr int LOGO_BASE = 8;
extern const uint8_t LOGO_RAMP[17];  // its face's gradient: per row, a colour (high nibble) over the base where its dither (low) has bits
constexpr int LOGO_DEPTH = 3;
constexpr int LOGO_SIDE = 7;
extern const uint8_t YOUWON1[240];  // PPOT lettering 119x16, MSB-first rows
constexpr int YOUWON1_W = 119;
extern const uint8_t YOUWON2[224];  // PPOT lettering 107x16, MSB-first rows
constexpr int YOUWON2_W = 107;
extern const uint8_t BROKE1[192];  // PPOT lettering 91x16, MSB-first rows
constexpr int BROKE1_W = 91;
extern const uint8_t BROKE2[160];  // PPOT lettering 73x16, MSB-first rows
constexpr int BROKE2_W = 73;
extern const uint8_t CHIP_TOP[37];  // chip_top 15x6, row spans
extern const uint8_t CHIP_SIDE[25];  // chip_side 15x4, row spans
extern const uint8_t CHIP_SIDE_ALT[25];  // chip_side_alt 15x4, row spans
