// GENERATED by tools/assets.py - do not edit.
// The dealer derives from Press-Play-On-Tape/Blackjack (Apache-2.0) by
// filmote & vampirics, recoloured 2026 for CHGame by bateske (CHBlackjack).
// See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t DEALER[463];
extern const uint8_t FACE_NORMAL[122];
extern const uint8_t CHIP_TOP[37];
extern const uint8_t CHIP_SIDE[25];
extern const uint8_t CHIP_SIDE_ALT[25];
extern const uint8_t CHIP_SMALL_TOP[31];
extern const uint8_t CHIP_SMALL_SIDE[15];
extern const uint8_t CHIP_SMALL_SIDE_ALT[15];
extern const uint8_t LOGO[345];
constexpr int LOGO_W = 113;
constexpr int LOGO_H = 23;
constexpr int LOGO_BASE = 8;
extern const uint8_t LOGO_RAMP[23];
constexpr int LOGO_DEPTH = 2;
constexpr int LOGO_SIDE = 7;
extern const uint16_t FACE_EDITS[196];
extern const uint16_t FACE_EDIT_AT[7];
