/* Generated by tools/icons.py from the PNGs in art/icons: edit those, then run it.
 * The visual menu's built-in screens, 12x12, a row a word, bit 15 leftmost. */
#ifndef CHBOOT_ICONS_H
#define CHBOOT_ICONS_H
#include <stdint.h>

#define ICON_W 12
#define ICON_H 12
#define ICON_GAME   0   /* a game without a picture; the program in flash */
#define ICON_FOLDER 1   /* a folder without a cover; no games (no card, no GAMES folder, or nothing in it) */
#define ICON_ERROR  2   /* an install error */
#define ICON_USB    3   /* USB upload */
#define ICON_OK     4   /* the dry run's check passed (build.sh app) */

static const uint16_t icons[][ICON_H] = {
    { 0x0000, 0x7FC0, 0x4060, 0x5F20, 0x5120, 0x5120, 0x5F20, 0x4020, 0x4020, 0x7FE0, 0x2AA0, 0x0000 },   /* game */
    { 0x0000, 0x7800, 0x4FE0, 0x4020, 0x5FE0, 0x5030, 0x6020, 0x6020, 0x4020, 0x7FE0, 0x0000, 0x0000 },   /* folder */
    { 0x0600, 0x0F00, 0x0900, 0x1980, 0x1680, 0x36C0, 0x2640, 0x6060, 0x4620, 0xFFF0, 0x0000, 0x0000 },   /* error */
    { 0x1F80, 0x1680, 0x1080, 0x1680, 0x3FC0, 0x2040, 0x2040, 0x2040, 0x3FC0, 0x0600, 0x0600, 0x0600 },   /* usb */
#if CHBOOT_APP
    { 0x0000, 0x0010, 0x0030, 0x0060, 0x00C0, 0x4180, 0x6300, 0x3600, 0x1C00, 0x0800, 0x0000, 0x0000 },   /* ok */
#endif
};

#endif
