// CHFour - FOUR IN A ROW for the CHGame handheld (CH32X035, 128x128 ST7735,
// piezo), in the look of CHBlackjack and its sister tables, against that
// game's dealer - who talks.
//
// The files:
//   Rules.*               the board and the rules: bitboards, nothing else
//   Ai.*                  the CPU: an alpha-beta search, a slice a tick
//   Game.*, Taunt.*       a game's flow, and what the dealer says about it
//   Stage.*, Table.*      the play screen: falling discs, the dealer, the camera
//   Screens.*, Frame.*    title, setup, play, options; the frame loop
//   Font.*, Fx.*          the display font; particles and banners
//   Sounds.*, Save.*      the sound effects; what a save holds
//   config.h              build switches
//   src/assets/           the art, generated by tools/assets.py
#include <CHGame.h>
#include "config.h"
#include "Frame.h"

void setup() {
    chgame.boot();
    gfx_begin(GFX_DIV2, GFX_12BPP);
    frame::begin();
    chgame.setFrameRate(CHF4_FPS);
}

void loop() {
    frame::run();
}
