// GENERATED by tools/assets.py - do not edit.
// Suit glyphs by Press Play On Tape (Apache-2.0), via CHBlackjack; card
// ranks, pips and court portraits from CHBlackjack; the glove from
// CHChess. See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t SUIT_SMALL[20];
extern const uint8_t RANK_GLYPH[91];
extern const uint8_t RANK_WIDTH[13];
extern const uint8_t PIP9[132];
extern const uint16_t PIP9_AT[4];
extern const uint8_t PIP13[178];
extern const uint16_t PIP13_AT[4];
extern const uint8_t COURT_JACK[117];
extern const uint8_t COURT_QUEEN[109];
extern const uint8_t COURT_KING[133];
extern const uint8_t LOGO[435];
constexpr int LOGO_W = 113;
constexpr int LOGO_H = 29;
constexpr int LOGO_BASE = 8;
extern const uint8_t LOGO_RAMP[29];
constexpr int LOGO_DEPTH = 3;
constexpr int LOGO_SIDE = 7;
extern const uint8_t HAND[111];
constexpr int HAND_TIP = 5;
extern const uint8_t CHIP9_TOP[29];
extern const uint8_t CHIP9_SIDE[19];
extern const uint8_t CHIP9_SIDE_ALT[19];
