#!/usr/bin/env python3
"""The visual menu's built-in screens: art/icons/*.png -> src/icons.h.

    python3 tools/icons.py            write src/icons.h from the PNGs
    python3 tools/icons.py --check    exit 1 if src/icons.h is not what the PNGs give
    python3 tools/icons.py --init     draw the first PNGs (never overwrites one)

Each icon is a 12x12 PNG with two colours: lit pixels are any colour brighter
than mid-grey, the rest is background. The bootloader draws an icon eight times
its size on black in colour 15 (the rainbow, or magenta in the Static style)
whenever it has a screen to show and the card cannot give the picture for it
(GAMES/SYSTEM.PIC, spec/card.md): with no card, on the USB-request path,
which never reads the card, and for a card without SYSTEM.PIC. Edit the PNGs
in any paint program and run this; src/icons.h is never edited by hand.
"""
import pathlib
import sys

from PIL import Image

HERE = pathlib.Path(__file__).resolve().parents[1]
ART = HERE / "art" / "icons"
OUT = HERE / "src" / "icons.h"
SIZE = 12
# In the order of the ICON_* numbers the bootloader uses (src/visual.c)
NAMES = ["game", "folder", "error", "usb", "ok"]
WHAT = {
    "game": "a game without a picture; the program in flash",
    "folder": "a folder without a cover; no games (no card, no GAMES folder, or nothing in it)",
    "error": "an install error",
    "usb": "USB upload",
    "ok": "the dry run's check passed (build.sh app)",
}

# The first drawings (--init): '#' lit, '.' background.
DRAFTS = {
    "game": """
............
.#########..
.#.......##.
.#.#####..#.
.#.#...#..#.
.#.#...#..#.
.#.#####..#.
.#........#.
.#........#.
.##########.
..#.#.#.#.#.
............""",
    "folder": """
............
.####.......
.#..#######.
.#........#.
.#.########.
.#.#......##
.##.......#.
.##.......#.
.#........#.
.##########.
............
............""",
    "error": """
.....##.....
....####....
....#..#....
...##..##...
...#.##.#...
..##.##.##..
..#..##..#..
.##......##.
.#...##...#.
############
............
............""",
    "usb": """
...######...
...#.##.#...
...#....#...
...#.##.#...
..########..
..#......#..
..#......#..
..#......#..
..########..
.....##.....
.....##.....
.....##.....""",
    "ok": """
............
...........#
..........##
.........##.
........##..
.#.....##...
.##...##....
..##.##.....
...###......
....#.......
............
............""",
}


def init():
    ART.mkdir(parents=True, exist_ok=True)
    for name in NAMES:
        f = ART / f"{name}.png"
        if f.exists():
            print(f"kept {f.relative_to(HERE)}")
            continue
        rows = DRAFTS[name].split()
        assert len(rows) == SIZE and all(len(r) == SIZE for r in rows), name
        im = Image.new("1", (SIZE, SIZE))
        im.putdata([1 if ch == "#" else 0 for r in rows for ch in r])
        im.save(f)
        print(f"drew {f.relative_to(HERE)}")


def bits(name):
    im = Image.open(ART / f"{name}.png").convert("L")
    if im.size != (SIZE, SIZE):
        raise SystemExit(f"art/icons/{name}.png: {im.size[0]}x{im.size[1]}, not {SIZE}x{SIZE}")
    px = im.tobytes()
    return [sum(0x8000 >> x for x in range(SIZE) if px[y * SIZE + x] >= 128) for y in range(SIZE)]


def header():
    out = ["/* Generated by tools/icons.py from the PNGs in art/icons: edit those, then run it.",
           f" * The visual menu's built-in screens, {SIZE}x{SIZE}, a row a word, bit 15 leftmost. */",
           "#ifndef CHBOOT_ICONS_H", "#define CHBOOT_ICONS_H", "#include <stdint.h>", "",
           f"#define ICON_W {SIZE}", f"#define ICON_H {SIZE}"]
    for i, name in enumerate(NAMES):
        out.append(f"#define ICON_{name.upper():7s}{i}   /* {WHAT[name]} */")
    out += ["", "static const uint16_t icons[][ICON_H] = {"]
    for name in NAMES:
        words = ", ".join(f"0x{w:04X}" for w in bits(name))
        if name == "ok":
            out.append("#if CHBOOT_APP")
        out.append(f"    {{ {words} }},   /* {name} */")
        if name == "ok":
            out.append("#endif")
    out += ["};", "", "#endif", ""]
    return "\n".join(out)


def main(argv):
    if "--init" in argv:
        init()
        return 0
    text = header()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("src/icons.h is not what art/icons/*.png give: run python3 tools/icons.py")
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(HERE)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
