"""Compose CHRoulette's music into Playtune bytes for CHGameSound.

    python tools/make_music.py      -> src/audio/Music.cpp

Each song is a tempo and up to four voices written as "NOTE:len" tokens,
lengths in eighth notes (default 1). NOTE is like C6, F#5, Bb6, or R for a
rest. Score bytes (CHGameSound / Arduboy Playtune): 0x9c n = note on in
channel c, 0x8c = note off, two bytes big-endian = wait ms, 0xE0 = restart,
0xF0 = stop. All tunes here are original; VICTORY and BROKE are CHBlackjack's.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "audio" / "Music.cpp"

NOTE = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}

SONGS = {
    # Title: a musette waltz in 3/4 (six eighths a bar), eight bars, loops.
    # The melody leans on chromatic neighbour notes, the accordion's way;
    # the accompaniment is oom-pah-pah as detached eighths an octave up,
    # where the piezo is as loud as the melody.
    "TITLE": dict(eighth_ms=150, voices=[
        "E6:2 D#6 E6 G6:2  C7:3 B6 A6:2  G6:2 F#6 G6 B6:2  D7:3 C7 B6:2 "
        "A6:2 G#6 A6 C7:2  B6:2 A6 G6 E6:2  F6:2 D6 B5 G5:2  C6:4 R:2",
        "C6 R E6 R G6 R  C6 R E6 R A6 R  D6 R G6 R B6 R  D6 R F6 R B6 R "
        "C6 R E6 R A6 R  C6 R E6 R G6 R  D6 R F6 R G6 R  C6 R E6 R G6 R",
    ]),
    # Won the game: fanfare, plays once.
    "VICTORY": dict(eighth_ms=110, voices=[
        "G6 G6 G6 C7:3 R G6 C7 E7:3 R C7 E7 G7:6 R:2 "
        "E7 F7 G7 A7 G7 E7 C7 E7 G7:8",
        "C6:3 R C6:3 R E6:3 R G6:6 R:2 C6:4 E6:4 C6:8",
    ]),
    # Broke: a slow minor blues, loops.
    "BROKE": dict(eighth_ms=260, voices=[
        "A6:2 G6:2 E6:2 D6:2 C6:4 A5:4  D6:2 C6:2 A5:2 G5:2 A5:8 "
        "E6:2 D6:2 C6:2 B5:2 A5:3 G#5 A5:4  R:8",
        "A6:4 E6:4 A6:4 E6:4  D6:4 A6:4 D6:4 A6:4 E6:4 B6:4 A6:8 R:8",
    ]),
}


def midi(tok):
    name = tok[0]
    rest = tok[1:]
    acc = 0
    while rest and rest[0] in "#b":
        acc += 1 if rest[0] == "#" else -1
        rest = rest[1:]
    octave = int(rest)
    return 12 * (octave + 1) + NOTE[name] + acc


def voice_events(text, eighth):
    t = 0
    ev = []
    for tok in text.split():
        note, _, n = tok.partition(":")
        dur = int(n or 1) * eighth
        if note != "R":
            ev.append((t, "on", midi(note)))
            ev.append((t + dur - 12, "off", None))      # short gap keeps notes distinct
        t += dur
    return ev, t


def compile_song(song, loop):
    eighth = song["eighth_ms"]
    all_ev = []
    total = 0
    for ch, v in enumerate(song["voices"]):
        ev, t = voice_events(v, eighth)
        total = max(total, t)
        all_ev += [(tm, 0 if kind == "off" else 1, ch, n) for tm, kind, n in ev]
    all_ev.sort(key=lambda e: (e[0], e[1]))
    out, now = [], 0
    for tm, on, ch, n in all_ev:
        if tm > now:
            wait = tm - now
            while wait > 0x7FFF:
                out += [0x7F, 0xFF]
                wait -= 0x7FFF
            out += [wait >> 8, wait & 0xFF]
            now = tm
        out += [0x90 | ch, n] if on else [0x80 | ch]
    if total > now:
        w = total - now
        out += [w >> 8, w & 0xFF]
    out.append(0xE0 if loop else 0xF0)
    return out


def main():
    loops = {"TITLE": True, "VICTORY": False, "BROKE": True}
    lines = ["// GENERATED by tools/make_music.py - do not edit. Original tunes (VICTORY and BROKE from CHBlackjack).",
             '#include "Music.h"', '#include "../../config.h"', "", "namespace music {", "",
             "// Debug builds (the test protocol: tools/device.py --debug, and the simulator) leave the scores",
             "// out - the protocol needs the flash, and the tests never listen.",
             "#if !CHGAME_DEBUG"]
    names = []
    for name, song in SONGS.items():
        data = compile_song(song, loops[name])
        body = ",".join(f"0x{b:02X}" for b in data)
        chunks = [body[i:i + 100] for i in range(0, len(body), 100)]
        lines.append(f"static const uint8_t {name}[{len(data)}] = {{\n  " + "\n  ".join(chunks) + "\n};")
        names.append((name, len(data)))
    lines.append("#endif")
    lines.append("")
    lines.append("void get(uint8_t song, bool loop, const uint8_t *&data, size_t &n) {")
    lines.append("    (void)loop;")
    lines.append("#if !CHGAME_DEBUG")
    lines.append("    switch (song) {")
    for i, (name, n) in enumerate(names):
        lines.append(f"        case {i}: data = {name}; n = sizeof {name}; return;")
    lines.append("    }")
    lines.append("#else")
    lines.append("    (void)song;")
    lines.append("#endif")
    lines.append("    data = nullptr; n = 0;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace music")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: " + ", ".join(f"{n} {b} B" for n, b in names))


if __name__ == "__main__":
    main()
